kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: smoke-tests
spec:
  args:
  - name: namespace
  - name: route-name
  - name: route-url
  - name: api-token
    valueFrom:
      secretKeyRef:
        name: monitor-auth-secret
        key: token
  metrics:
  - name: success-rate
    interval: 30s
    count: 4
    successCondition: result[0] == 0
    failureLimit: 0
    provider:
      prometheus:
        address: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
        timeout: 40
        insecure: true
        headers:
          - key: Authorization
            value: "Bearer {{args.api-token}}"
        query: |
          irate(haproxy_backend_http_responses_total{exported_namespace='{{ args.namespace }}', route=~"{{ args.route-name }}", code="5xx"}[1m]) > 5 or on() vector(0)
  - name: run-load
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: siege
                image: quay.io/gnunn/tools:latest
                command: [sh, -c]
                args: ["siege -c 20 -r 15 -d10 -v http://{{args.route-url}}"]
              restartPolicy: Never
