apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: quay.io/thason/rollouts:purple
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 4
            memory: 6Gi
            requests:
              cpu: 2
              memory: 4Gi
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: active
      previewService: preview
      autoPromotionEnabled: false
