apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: active
spec:
  host: active-route-rollouts-prod.apps-crc.testing
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: active
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: preview
spec:
  host: preview-route-rollouts-prod.apps-crc.testing
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: preview
