{{ if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "rollouts-manager.fullname" . }}
  labels:
    {{- include "rollouts-manager.labels" . | nindent 4 }}
  annotations:
    link.argocd.argoproj.io/external-link: {{ include "dashboard.link" . }}
spec:
  host: {{ include "dashboard.host" . }}
  port:
    targetPort: {{ .Values.service.portName }}
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.route.tls.termination }}
  to:
    kind: Service
    name: {{ include "rollouts-manager.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end -}}
