apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollouts-demo
  name: active
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: rollouts-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollouts-demo
  name: preview
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: rollouts-demo
