apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rollouts-demo
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rollouts-demo
